# This file is a template, and might need editing before it works on your project.
# https://hub.docker.com/r/google/dart
image: cirrusci/flutter:2.10.4

## Cache downloaded dependencies and plugins between builds.
## To keep cache across branches add 'key: "$CI_JOB_NAME"'
#cache:
#  paths:
#    - .pub-cache/global_packages

stages:
  - format_analyze_test

format_analyze_test:
  stage: format_analyze_test
  script:
    - dart format -l 150 --set-exit-if-changed .
    - flutter clean
    - flutter pub get
    - fv2 pub run dependency_validator
    - flutter analyze
    - flutter test
