# This file is a template, and might need editing before it works on your project.
image: cirrusci/flutter:3.0.1

## Cache downloaded dependencies and plugins between builds.
## To keep cache across branches add 'key: "$CI_JOB_NAME"'
#cache:
#  paths:
#    - .pub-cache/global_packages

stages:
  - format_analyze_test

format_analyze_test:
  stage: format_analyze_test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  script:
    - dart format -l 150 --set-exit-if-changed .
    - flutter clean
    - flutter pub get
    - flutter pub run dependency_validator
    - flutter pub run dart_code_metrics:metrics check-unused-code lib
    - flutter analyze
    - flutter test
