# This file is a template, and might need editing before it works on your project.
# https://hub.docker.com/r/google/dart
image: cirrusci/flutter:2.10.4

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

stages:
  - analyze_and_test

before_script:
  - flutter pub get

analyze_and_test:
  stage: analyze_and_test
  script:
    - flutter analyze
    - dart format --line-length 150 --set-exit-if-changed .