# This file is a template, and might need editing before it works on your project.
image:
  name: cirrusci/flutter:3.0.5

## Cache downloaded dependencies and plugins between builds.
## To keep cache across branches add 'key: "$CI_JOB_NAME"'
#cache:
#  paths:
#    - .pub-cache/global_packages

stages:
  - format_analyze_test
  - build

format_analyze_test:
  stage: format_analyze_test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  script:
    - dart format -l 150 --set-exit-if-changed .
    - flutter clean
    - flutter pub get
    - flutter pub run dependency_validator
    - flutter pub run dart_code_metrics:metrics check-unused-code lib
    - flutter pub run dart_code_metrics:metrics check-unused-files lib
    - flutter analyze
    - flutter test

#build:apk:
#  stage: build
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#      when: always
#  script:
#    - flutter build apk --release
#  artifacts:
#    name: "dev_release"
#    paths:
#      - build/app/outputs/apk/release
#
#build:appbundle:
#  stage: build
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
#      when: always
#  script:
#    - flutter build appbundle --release
#  artifacts:
#    name: "main_release"
#    paths:
#      - build/app/outputs/bundle/release