name: sportlab
description: Sport Lab mobile app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.2+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  get: ^4.6.5
  flutter_native_splash: ^2.3.4
  url_launcher: ^6.2.2
  flash: ^3.0.0
  get_storage: ^2.1.1
  pinput: ^4.0.0
  flutter_udid: ^3.0.0
  device_info_plus: ^10.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  webview_flutter: ^4.8.0
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.0.1
  geolocator: ^12.0.0
  location: ^6.0.2
  dio: ^5.4.3+1
  image_picker: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  dependency_validator: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_logo.png"
  min_sdk_android: 16
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/register/

  fonts:
    - family: Font_Awesome_6_Pro
      fonts:
        - asset: assets/font/Font Awesome 6 Pro-Light-300.otf
          weight: 300

        - asset: assets/font/Font Awesome 6 Pro-Regular-400.otf
          weight: 400

        - asset: assets/font/Font Awesome 6 Pro-Solid-900.otf
          weight: 900

    - family: GIP
      fonts:
        - asset: assets/font/GIP-Regular.otf
          weight: 400
        - asset: assets/font/GIP-Bold.otf
          weight: 700
        - asset: assets/font/GIP-Light.otf
          weight: 300


